# Generated by Django 4.0 on 2021-12-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reciept',
            new_name='Recipe',
        ),
    ]
